services:
  rabbit-mq-app:
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 6
    volumes:
      - rabbit-mq-data:/var/lib/rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_TAG:-ofcp}-rabbit-mq.tls=true"
      - "traefik.http.routers.${TRAEFIK_TAG:-ofcp}-rabbit-mq.middlewares=${TRAEFIK_TAG:-ofcp}-forward-auth"
      - "traefik.http.routers.${TRAEFIK_TAG:-ofcp}-rabbit-mq.rule=Host(`${MAIN_DOMAIN_PREFIX:-}rabbit-mq.${MAIN_DOMAIN}`)"
      - "traefik.http.services.${TRAEFIK_TAG:-ofcp}-rabbit-mq.loadbalancer.server.port=15672"
      - "traefik-app-dashboard.service=${TRAEFIK_TAG:-ofcp}-rabbit-mq"
      - "traefik-app-dashboard.img=https://www.rabbitmq.com/img/rabbitmq-logo-with-name.svg"

volumes:
  rabbit-mq-data:
