x-restart: &restart
  restart: ${RESTART}

include:
  - path:
      - ./docker/compose.proxy.yml

services:
  rabbit-mq-app:
    build:
      context: .
      dockerfile: Dockerfile
    <<: *restart
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro