x-restart: &restart
  restart: ${RESTART}

services:
  rabbit-mq-app:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 6
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro

  rabbit-mq-proxy:
    image: ghcr.io/scolastico-dev/s.containers/rabbitmq-auth-proxy:latest
    <<: *restart
    depends_on:
      rabbit-mq-app:
        condition: service_healthy
    environment:
      RABBITMQ_URL: http://rabbit-mq-app:15672
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_TAG:-ofcp}-rabbit-mq.tls=true"
      - "traefik.http.routers.${TRAEFIK_TAG:-ofcp}-rabbit-mq.middlewares=${TRAEFIK_TAG:-ofcp}-forward-auth"
      - "traefik.http.routers.${TRAEFIK_TAG:-ofcp}-rabbit-mq.rule=Host(`${MAIN_DOMAIN_PREFIX:-}rabbit-mq.${MAIN_DOMAIN}`)"
      - "traefik.http.services.${TRAEFIK_TAG:-ofcp}-rabbit-mq.loadbalancer.server.port=3000"
      - "traefik-app-dashboard.service=${TRAEFIK_TAG:-ofcp}-rabbit-mq"
      - "traefik-app-dashboard.img=https://www.rabbitmq.com/img/rabbitmq-logo-with-name.svg"