name: Build and push docker images to Container-Registry

on:
  push:
    branches:
      - main

jobs:
  buildAndPush:
    name: Build and push images to Container-Registry
    runs-on: ubuntu-latest
    steps:
      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Queue
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/tecsafe/rabbit-mq:latest
          build-args: TECSAFE_VERSION=${{ github.sha }}